import Head from 'next/head'
import { BsFillMoonStarsFill, BsSunFill, BsFillHeartFill } from 'react-icons/bs'
import { AiFillGithub, AiFillLinkedin } from 'react-icons/ai'
import { SiReact, SiMongodb, SiExpress  } from 'react-icons/si'
import Typed from 'react-typed'
import Fade from 'react-reveal/Fade'
import { useRef, useState } from 'react'
import emailjs from '@emailjs/browser'

import Image from 'next/image'
import avatar from '../../public/avatar.png'
import Projeto1 from '../../public/Projeto1.png'
import Soon from '../../public/Soon.png'
import Programmer from '../../public/programmer.svg'
import Card from '@/components/Card'

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  const form = useRef()
  
  const sendEmail = (e) => {
    e.preventDefault();

    emailjs.sendForm('service_j16rcu6', 'template_yt0jxyv', e.target, 'g1Kg0x-0Z-ugAwVja')
      .then((result) => {
          alert('Mensagem Enviada ;)!');
      }, (error) => {
          alert(error.text);
      });
      e.target.reset()
  };
  
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Guilherme Alves Portifolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className="h-full w-full                                                                   transition-all bg-day bg-fixed bg-no-repeat bg-cover bg-center dark:bg-night">
          <Fade bottom>
          <section className='min-h-screen dark:text-white'>
            <nav className='px-10 py-10 mb-12 flex justify-between'>
              <h1 className='text-xl font-burtons'>developedbyalves</h1>
              <ul className='flex items-center'>
                <li>
                  {darkMode ? <BsSunFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer transition-all text-2xl text-white hover:scale-150'/> : <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl transition-all hover:scale-150'/>}
                </li>
              </ul>
            </nav>
            <div className='text-center p-10'>
              <h2 className='text-5xl py-2 text-red-900 font-medium dark:text-rose-100'>Guilherme Alves</h2>
              <div className='text-3xl py-2 text-red-900 dark:text-rose-100'>
                <Typed strings={["Desnevolerd", "Desenvolvedor Wav", "Desenvolvedor Web"]}
                typeSpeed={20}
                backSpeed={50}
                backDelay={2000}
                loop/>
              </div>
              <p className='text-xl py-5 leading-8 text-red-900 dark:text-rose-100'>
                Desenvolvedor Web apaixonado por tecnologia confira meus trabalhos abaixo.
              </p>
            </div>
            <div className='text-5xl flex justify-center gap-16 py-3 text-white'>
              <AiFillGithub/>
              <AiFillLinkedin/>
            </div>
            <div className='relative my-10 mx-auto bg-gradient-to-b from-red-500 rounded-full w-80 h-80 mt-20 overflow-hidden dark:from-blue-600'>
              <Image src={avatar} layout="fill" objectFit='cover'/>
            </div>
          </section>
        </Fade>
        <Fade bottom>
        <section className='m-10 rounded-xl bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60 justify-center p-5'>
          <h3 className='text-7xl py-1 text-slate-300 font-bold'>Sobre Mim</h3>
              <div className='flex mr-5'>
                <p className='mt-5 text-3xl py-2 leading-8 text-rose-50'>
                  Desde criança sou apaixonado por progamação e arte, quando cresci não foi diferente.<br/> Com meus 13 anos descobri a Unity 3D e já começava a programar meus primeiros joguinhos com o C# e meu sonho sempre foi me tornar um desenvolvedor de jogos,<br/> mas o tempo passou e em 2021 tive novamente o contato com a programação
                  Hoje tenho 20 anos e sou um desenvolver web e mobile, ultilizo do <span className='text-teal-500'>React</span> e <span className='text-teal-500'>React Native</span>, <span className='text-teal-500'>Express</span> e <span className='text-teal-500'>Mongo</span> para fazer minhas aplicações
                  e estou a procura da minha primeira vaga.
                </p>
              <div className='sm:hidden md:hidden lg:block max-sm:hidden'>
              <Image src={Programmer}/>
              </div>
            </div>
            <div className='flex justify-center gap-16 my-1'>
                <SiReact className='text-teal-900' size={100}/>
                <SiExpress size={100}/>
                <SiMongodb className='text-green-900' size={100}/>
            </div>
          </section>
        </Fade>
        <Fade bottom>
          <section className='m-10 p-10 rounded-xl bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60'>
            <div className='flex flex-col justify-center items-center mt-40'>
              <h3 className='text-7xl py-1 text-slate-300 font-bold'>Projetos</h3>
              <h4 className='text-2xl py-3 text-rose-50'>Confira alguns dos projetos que eu desenvolvi.</h4>
            </div>
            <div className='mt-7 grid place-items-center gap-32 lg:grid-cols-3 md:grid-cols-2 max-sm:grid-cols-1'>
              <Fade bottom>
                <Card imge={Projeto1} link='https://apple-cart-demo.vercel.app' title="Loja Apple" subtitle="Front-End de uma loja de iPhones usando React e Tailwind CSS e ultilizando a API do Mercado Livre"/>
                <Card imge={Soon} title="Em breve..." subtitle="Projeto sendo desenvolvido"/>
                <Card imge={Soon} title="Em breve..." subtitle="Projeto sendo desenvolvido"/>
              </Fade>
            </div>
          </section>
        </Fade>
        <Fade bottom>
          <section className='m-10 rounded-xl bg-clip-padding backdrop-filter backdrop-blur-xl bg-opacity-60'>
            <div className='flex flex-col justify-center items-center mt-40'>
              <h3 className='text-7xl py-1 text-slate-300 font-bold'>Contato</h3>
              <h4 className='text-2xl py-3 text-rose-50'>Gostou do que viu? Entre em contato</h4>
            </div>
            <div class="p-10 mr-auto ml-auto w-full max-w-[550px]">
              <form onSubmit={sendEmail}>
                <div class="mb-5">
                  <label
                    for="name"
                    class="mb-3 block text-base font-medium text-rose-100"
                  >
                    Nome
                  </label>
                  <input
                    type="text"
                    name="name"
                    id="name"
                    placeholder="Nome"
                    class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                  />
                </div>
                <div class="mb-5">
                  <label
                    for="email"
                    class="mb-3 block text-base font-medium text-rose-100"
                  >
                    Email
                  </label>
                  <input
                    type="email"
                    name="email"
                    id="email"
                    placeholder="exemplo@exemplo.com"
                    class="w-full rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                  />
                </div>
                <div class="mb-5">
                  <label
                    for="message"
                    class="mb-3 block text-base font-medium text-rose-100"
                  >
                    Mensagem
                  </label>
                  <textarea
                    rows="4"
                    name="message"
                    id="message"
                    placeholder="Digite sua mensagem"
                    class="w-full resize-none rounded-md border border-[#e0e0e0] bg-white py-3 px-6 text-base font-medium text-[#6B7280] outline-none focus:border-[#6A64F1] focus:shadow-md"
                  ></textarea>
                </div>
                <div>
                  <button
                    type='submit'
                    value='Send'
                    class="hover:scale-110 transition-all rounded-md bg-[#6A64F1] py-3 px-8 text-base font-semibold text-white outline-none"
                  >
                    Enviar
                  </button>
                </div>
              </form>
            </div>
          </section>
        </Fade>
        <footer>
          <div className='w-screen h-14 flex justify-center items-center'>
            <p className='text-white flex text-bold text-xl'>
                Feito com <BsFillHeartFill color='red' />  por Guilherme Alves
            </p>
            
          </div>
        </footer>
      </main>
    </div>
  )
}
